# TCL File Generated by Component Editor 17.0
# Fri Jan 26 23:58:51 BRST 2018
# DO NOT MODIFY


# 
# delay "delay" v1.0
#  2018.01.26.23:58:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module delay
# 
set_module_property DESCRIPTION ""
set_module_property NAME delay
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME delay
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL delay30fps
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file delay30fps.v VERILOG PATH delay/delay30fps.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point delay_instr
# 
add_interface delay_instr nios_custom_instruction end
set_interface_property delay_instr clockCycle 0
set_interface_property delay_instr operands 2
set_interface_property delay_instr ENABLED true
set_interface_property delay_instr EXPORT_OF ""
set_interface_property delay_instr PORT_NAME_MAP ""
set_interface_property delay_instr CMSIS_SVD_VARIABLES ""
set_interface_property delay_instr SVD_ADDRESS_GROUP ""

add_interface_port delay_instr dataa dataa Input 32
add_interface_port delay_instr datab datab Input 32
add_interface_port delay_instr result result Output 32
add_interface_port delay_instr clk clk Input 1
add_interface_port delay_instr clk_en clk_en Input 1
add_interface_port delay_instr start start Input 1
add_interface_port delay_instr reset reset Input 1
add_interface_port delay_instr done done Output 1

